### ISSUE TITLE
MyEntityComponentContainer Wiki page

### ISSUE THREAD

**Issue by DontNuts** [malware-dev/MDK-SE#138]
In the [IMyEntity.Components](https://github.com/malware-dev/MDK-SE/wiki/VRage.Game.ModAPI.Ingame.IMyEntity.Components) page, when I click on the [MyEntityComponentContainer](https://github.com/malware-dev/MDK-SE/wiki/VRage.Game.Components.MyEntityComponentContainer) link, it redirected me to the [Home](https://github.com/malware-dev/MDK-SE/wiki) page, is it normal?

Hm... This [MyEntityComponentBase](https://github.com/malware-dev/MDK-SE/wiki/VRage.Game.Components.MyEntityComponentBase) too...

**Comment by malware-dev** [comment]
Those types are probably not whitelisted directly, which means no page will be generated for them. There's something fishy about those types. I really despise partially whitelisted types... 😒

**Comment by DontNuts** [comment]
(A wiki page link outdated...)
In [The Runtime](https://github.com/malware-dev/mdk-se/wiki/The-Runtime) and [Do's and Don'ts](https://github.com/malware-dev/mdk-se/wiki/Do's-and-Don'ts), there is a link that points to [Here](https://github.com/malware-dev/MDK-SE/wiki/Advanced:-Easy-and-Powerful-State-Machine-Using-%22yield-return%22), but I guess that should point to [There](https://github.com/malware-dev/mdk-se/wiki/Coroutines---Run-operations-over-multiple-ticks) instead...

**Comment by malware-dev** [comment]
Awesome, thank you, fixed! I would have preferred a separate post though, as it's a different issue 😉

**Comment by DontNuts** [comment]
Hmm.. the link in [The Runtime](https://github.com/malware-dev/mdk-se/wiki/The-Runtime) isn't fixed though...

> Advanced users can [see here](https://github.com/malware-dev/MDK-SE/wiki/Advanced:-Easy-and-Powerful-State-Machine-Using-%22yield-return%22) for a very useful trick to ...

By the way, I think those "issues" are too small to be an issue.. if I open a new post for each "wiki correction", that would be flooding the issues page.
For example the VRage.Game.MyDefinitionBase is missing a page too, but I don't know if it is worth its own page because there's only one method (ToString) can be used in programmable block, other methods seem to be prohibited.
For your reference.. this thing is mentioned in [RemainingBlocksPerType](https://github.com/malware-dev/MDK-SE/wiki/Sandbox.ModAPI.Ingame.IMyProjector.RemainingBlocksPerType), the return value is of type "Dictionary<VRage.Game.MyDefinitionBase, System.Int32>" (with a mysterious 404 link to M$..)

As I guess that the pages may be kind of auto-generated in some way, so forget it man..

P.S. I can delete the post after you read it.

**Comment by malware-dev** [comment]
It's much easier to keep track because you can't always do it all at once. I don't ask for this on a whim 🙂 Deleting posts is also a bad idea because then I lose historical tracking. All of this is pretty standard for support sites. There's always a preference for one bug, one post.

Yes, the API list is autogenerated and types that are not whitelisted do not get their own page - on purpose. There's just one bug there - either that it creates the link in the first place and shouldn't, or that the whitelist is only allowing the base type itself, no members, and my generator doesn't handle that well. 

Somehow I missed your reference to The Runtime, I'll fix that too, thank you 😄
