### ISSUE TITLE
Wiki - Question about API limits

### ISSUE THREAD

**Issue by MagboneD** [malware-dev/MDK-SE#164]
It appears that inert (armor) blocks are not accessible via the API. Or  have I missed something? 

I'm new to SE and returning to coding after a long absence (although I worked professionally writing business software for a number of years and a hobbyist since early teens). 

I wanted to optimize blueprint production and write a script that would let me mass-replace all light armor blocks with heavy variants and vice-versa, or exchange fully constructed blocks for partially constructed. Is this possible with the current API?

**Comment by malware-dev** [comment]
Correct, you can only access functional blocks in the programmable block API. This is by design. I am afraid there's also no access to blueprints in the programmable block API.

I must ask you to direct scripting questions to Keen's discord or their forums (the former being recommended, you'll usually find me there too). _This_ page is reserved for issues about MDK itself (or the wiki of course) and is not intended to provide help for scripting. I am sorry, but I am just one person :-D 

---- MagboneD wrote ----

**Comment by MagboneD** [comment]
No problem. Thanks for the response.
