### ISSUE TITLE
Capability of Running Unit Tests

### ISSUE THREAD

**Issue by pedrohugorm** [malware-dev/MDK-SE#192]
This is more of a request than an Issue.

I'd like the capability of being able to run NUnit or some other Unit Testing framework.
I was able to setup NUnit fine and use its features, but once I run the test on my IDE the test never runs - It shows "Inconclusive" all the time. 

I'm wondering if it's related to the analyzer or some of the project's setup.

Any workarounds?
Any Tips?
Or is this something that requires a change on MDK?

**Comment by malware-dev** [comment]
I have been successfully running NUnit tests on the MDK since I first made it, it's designed specifically to be unit testable... so I'm afraid I don't really have an answer to you. There must be some kind of setup problem.

**Comment by malware-dev** [comment]
Wait... It _does_ ring a bell...

Something about NUnit not finding the game assemblies...?

**Comment by malware-dev** [comment]
Hm. No. That situation makes it simply go "Failed"...

**Comment by malware-dev** [comment]
You could always run your tests from the Bootstrapper.cs. That's set up to run, and load game assemblies, after all.

Any file in the MDK folder, and files with .Debug.cs extensions, will be ignored by the deployer.

**Comment by malware-dev** [comment]
Hm. Interesting. I'm now seeing the same issue _you_ are.

**Comment by malware-dev** [comment]
I'm very sorry. I'm stumped on this, something has clearly changed since I last run unit tests on a script... and my Google Fu fails me as well. I fear I don't have time to go in-depth into this :(

**Comment by pedrohugorm** [comment]
Turns out I figured out a way:

I created an NUnit project that didn't use the MDK framework but adds the references directly from the game folder:

![image](https://user-images.githubusercontent.com/847076/80768547-4dd89a80-8b10-11ea-8b45-a14e7518b1b7.png)

And that did the trick.

**Comment by kwilliams1987** [comment]
Maybe useful to add an MDK Unit Test project type with the same reference
binding mechanisms as the standard project but no whitelisting?

**Comment by alex-davidson** [comment]
I've run into this issue too. I'll see about diagnosing it properly at some stage and submit a PR for adding unit testing to the project template maybe (seems it should be possible to put a Tests dir under MDK...) but *after* I've recovered from grovelling through MSBuild scripts.

Meanwhile, I've tried using a separate UnitTests project and referencing the script project from there, and noted that importing the `MDK.paths.props` from the script project *seems* to work, except for `Private` being `false` (the test adaptor objects to dependencies being absent from the output directory). Add the following to the test project .csproj, just before the closing `</Project>` tag:

*WARNING: Ugly hack follows*
```
  <Import Project="<path-to-script-project>/MDK/MDK.paths.props" Condition="exists('<path-to-script-project>/MDK/MDK.paths.props')" />
  <ItemGroup>
    <Analyzer Remove="$(MDKInstallPath)\Analyzers\MDKAnalyzer.dll" />
  </ItemGroup>
  <PropertyGroup>
    <PrepareProjectReferencesDependsOn>$(PrepareProjectReferencesDependsOn);CopyGameFilesLocally</PrepareProjectReferencesDependsOn>
  </PropertyGroup>
  <Target Name="CopyGameFilesLocally" BeforeTargets="PrepareProjectReferences" Condition="'$(MDKGameBinPath)' != ''">
    <ItemGroup>
      <Reference Update="@(Reference)" Condition="$([System.String]::new('%(Reference.HintPath)').StartsWith('$(MDKGameBinPath)\'))">
        <Private>True</Private>
      </Reference>
    </ItemGroup>
  </Target>
```

Which is why adding references directly also works: they're CopyLocal by default.

So:
* Something odd about putting tests in the script project; test adaptor won't even try to run them.
* Separate test project works fine, but tests fail because game binaries aren't copied to the output folder.
* Forcing game binaries to be in the output folder allows tests to work.
* Conclusion: including tests in the script project is likely to require `<Private>True</Private>` in the paths props file, in addition to fixing the existing test adaptor breakage.
