### ISSUE TITLE
Questions about appdomains, and other technical things

### ISSUE THREAD

**Issue by distantcam** [malware-dev/MDK-SE#250]
Hi! First off, great project! As a long-time C# dev it's great to be able to use VS to edit scripts.

While developing scripts I've had a few technical questions I'd like to ask.

First up, do you know if the programmable block runs all the scripts in the same appdomain, or does each block/script get it's own appdomain?
Do you think it would be possible to side-load other assemblies into the scripts domain?

I also have some questions about this extension. I'm assuming somewhere in the code the rosyln C# project workspace is loaded from VS, and then something runs to generate all the output files. Would it be possible to extract that for use in the msbuild engine instead of directly in VS? I'm happy to do that work I just need a bit of guidance as to where all that code is in this project.

Thanks

**Comment by malware-dev** [comment]
All scripts are run in the same appdomain.

You will find the build code in Mdk/Build.

The code has not been designed to be separated, mind you.

Also note that others have been asking for a separated tool as well, so if you want to make it a part of the MDK-SE project for others to use too, I am sure they will be very grateful. Obviously you will be fully credited for that work.

You might find it easier to communicate with me through Keen's discord rather than here.
