### ISSUE TITLE
This extension is not installable on any installed products-Visual studio 2022

### ISSUE THREAD

**Issue by Valduis4** [malware-dev/MDK-SE#251]
Here is the install log.  I think the new visual studio does not support this or most likely I am doing something wrong.  I do have the framework installed.
`11/22/2021 8:57:22 PM - Microsoft VSIX Installer
11/22/2021 8:57:22 PM - -------------------------------------------
11/22/2021 8:57:22 PM - vsixinstaller.exe version:
11/22/2021 8:57:22 PM - 17.0.5226-preview5
11/22/2021 8:57:22 PM - -------------------------------------------
11/22/2021 8:57:22 PM - Command line parameters:
11/22/2021 8:57:22 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\*****\Downloads\Done Herbert\MDK.vsix
11/22/2021 8:57:22 PM - -------------------------------------------
11/22/2021 8:57:22 PM - Microsoft VSIX Installer
11/22/2021 8:57:22 PM - -------------------------------------------
11/22/2021 8:57:22 PM - Initializing Install...
11/22/2021 8:57:22 PM - Extension Details...
11/22/2021 8:57:22 PM - 	Identifier         : MDK.Morten Aune Lyrstad.e02b602e-3099-44a5-88c6-cb30cab978f6
11/22/2021 8:57:22 PM - 	Name               : MDK/SE
11/22/2021 8:57:22 PM - 	Author             : Morten Aune Lyrstad
11/22/2021 8:57:22 PM - 	Version            : 1.4.12
11/22/2021 8:57:22 PM - 	Description        : A toolkit to help with ingame script (programmable block) development for Keen Software House's space sandbox Space Engineers.

Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
11/22/2021 8:57:22 PM - 	Locale             : en-US
11/22/2021 8:57:22 PM - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
11/22/2021 8:57:22 PM - 	InstalledByMSI     : False
11/22/2021 8:57:22 PM - 	SupportedFrameworkVersionRange : [4.6.1,)
11/22/2021 8:57:22 PM - 
11/22/2021 8:57:22 PM - 	SignatureState     : Unsigned
11/22/2021 8:57:22 PM - 	Supported Products : 
11/22/2021 8:57:22 PM - 		Microsoft.VisualStudio.Community
11/22/2021 8:57:22 PM - 			Version : [16.8,17.0)
11/22/2021 8:57:22 PM - 			ProductArchitecture : x86
11/22/2021 8:57:22 PM - 
11/22/2021 8:57:22 PM - 	References         : 
11/22/2021 8:57:22 PM - 	Prerequisites      : 
11/22/2021 8:57:22 PM - 		-------------------------------------------------------
11/22/2021 8:57:22 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
11/22/2021 8:57:22 PM - 		Name         : Visual Studio core editor
11/22/2021 8:57:22 PM - 		Version      : [15.0,)
11/22/2021 8:57:22 PM - 
11/22/2021 8:57:22 PM - 		-------------------------------------------------------
11/22/2021 8:57:22 PM - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
11/22/2021 8:57:22 PM - 		Name         : Roslyn Language Services
11/22/2021 8:57:22 PM - 		Version      : [15.0,)
11/22/2021 8:57:22 PM - 
11/22/2021 8:57:22 PM - Signature Details...
11/22/2021 8:57:22 PM - 	Extension is not signed.
11/22/2021 8:57:22 PM - 
11/22/2021 8:57:22 PM - Searching for applicable products...
11/22/2021 8:57:22 PM - Found installed product - Global Location
11/22/2021 8:57:22 PM - Found installed product - Visual Studio Community 2022
11/22/2021 8:57:22 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
`

**Comment by malware-dev** [comment]
https://github.com/malware-dev/MDK-SE#visual-studio-2022-support

Sorry.

**Comment by zalimitless** [comment]
Which 2019 version would you suggest we run this on?
The latest 2019 version is giving the same issues.

**Comment by zalimitless** [comment]
Just for reference, here is the problem that I am experiencing:

`1/6/2022 1:43:30 PM - Microsoft VSIX Installer
1/6/2022 1:43:30 PM - -------------------------------------------
1/6/2022 1:43:30 PM - vsixinstaller.exe version:
1/6/2022 1:43:30 PM - 16.11.12
1/6/2022 1:43:30 PM - -------------------------------------------
1/6/2022 1:43:30 PM - Command line parameters:
1/6/2022 1:43:30 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\jvdla\Downloads\MDK.vsix
1/6/2022 1:43:30 PM - -------------------------------------------
1/6/2022 1:43:30 PM - Microsoft VSIX Installer
1/6/2022 1:43:30 PM - -------------------------------------------
1/6/2022 1:43:31 PM - Skipping product Microsoft.VisualStudio.Product.BuildTools (00781cb4) since it does not support extensions
1/6/2022 1:43:31 PM - Initializing Install...
1/6/2022 1:43:31 PM - Extension Details...
1/6/2022 1:43:31 PM - 	Identifier         : MDK.Morten Aune Lyrstad.e02b602e-3099-44a5-88c6-cb30cab978f6
1/6/2022 1:43:31 PM - 	Name               : MDK/SE
1/6/2022 1:43:31 PM - 	Author             : Morten Aune Lyrstad
1/6/2022 1:43:31 PM - 	Version            : 1.4.12
1/6/2022 1:43:31 PM - 	Description        : A toolkit to help with ingame script (programmable block) development for Keen Software House's space sandbox Space Engineers.

Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
1/6/2022 1:43:31 PM - 	Locale             : en-US
1/6/2022 1:43:31 PM - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
1/6/2022 1:43:31 PM - 	InstalledByMSI     : False
1/6/2022 1:43:31 PM - 	SupportedFrameworkVersionRange : [4.6.1,)
1/6/2022 1:43:31 PM - 
1/6/2022 1:43:31 PM - 	SignatureState     : Unsigned
1/6/2022 1:43:31 PM - 	Supported Products : 
1/6/2022 1:43:31 PM - 		Microsoft.VisualStudio.Community
1/6/2022 1:43:31 PM - 			Version : [16.8,17.0)
1/6/2022 1:43:31 PM - 
1/6/2022 1:43:31 PM - 	References         : 
1/6/2022 1:43:31 PM - 	Prerequisites      : 
1/6/2022 1:43:31 PM - 		-------------------------------------------------------
1/6/2022 1:43:31 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/6/2022 1:43:31 PM - 		Name         : Visual Studio core editor
1/6/2022 1:43:31 PM - 		Version      : [15.0,)
1/6/2022 1:43:31 PM - 
1/6/2022 1:43:31 PM - 		-------------------------------------------------------
1/6/2022 1:43:31 PM - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
1/6/2022 1:43:31 PM - 		Name         : Roslyn Language Services
1/6/2022 1:43:31 PM - 		Version      : [15.0,)
1/6/2022 1:43:31 PM - 
1/6/2022 1:43:31 PM - Signature Details...
1/6/2022 1:43:31 PM - 	Extension is not signed.
1/6/2022 1:43:31 PM - 
1/6/2022 1:43:31 PM - Searching for applicable products...
1/6/2022 1:43:31 PM - Found installed product - Global Location
1/6/2022 1:43:31 PM - Found installed product - Visual Studio Community 2019
1/6/2022 1:43:31 PM - Found installed product - Visual Studio Community 2017 (2)
1/6/2022 1:43:31 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
`

**Comment by malware-dev** [comment]
Given that I'm (always) running the latest versions myself, you must have some other local problem I don't know about.

Are you _sure_ your Visual Studio is actually up to date?

**Comment by zalimitless** [comment]
Thanks for the response.
Just to be 100% sure, I will be re-installing everything to the latest 2019 version.

**Comment by malware-dev** [comment]
I am working now, but I will try to remember to test a clean installation into VS2019 later tonight. As you say, to be 100% sure.

I _am_ working on a 2022 version but it'll take time, I'm afraid.

**Comment by malware-dev** [comment]
I just tried to install this in my fully updated VS2019, and that worked just fine.

**Comment by zalimitless** [comment]
Thank you @malware-dev I believe it is because I installed VS2022 first a few months ago, then reinstalled VS2019 without uninstalling VS2022.
Haven't tried again, but will soon.

**Comment by malware-dev** [comment]
That _is_ possible, but I too have a dual installation of '22 and '19 - although I installed '22 after '19.

**Comment by zalimitless** [comment]
After a CLEAN installation of VS2019 it worked perfectly fine.

Thank you for helping out @malware-dev
