### ISSUE TITLE
[Feature Request] Port to VS Studio Community 2022

### ISSUE THREAD

**Issue by Chaos02** [malware-dev/MDK-SE#260]
Title says it all - please make available for installation in VS Studio 2022

**Comment by malware-dev** [comment]
I did indeed. Sadly I don't have much in terms of motivation to be working on this these days.

**Comment by SolarVampire** [comment]
I want to beat this dead horse. Please don't hate on me for it either, I made an account just to leave this comment;

	I would find great value in a 2022 version as well. It's very hard to want to download multiple versions of visual studio, as a beginner I don't know if it's going to install all of the same packages and double up on them? Is it going to allow me to have both installations at the same time? How many other coding projects would benefit from v2019? It places me in a limbo where I've chosen to revert to notepad++ and manually reading the APIs. 
	To be fair, this WOULD drastically improve my understanding of them over time, by not using training wheels. However, the more experienced version of myself would appreciate a more streamlined environment. To be fair, honest and transparent, there's a good chance that this will just turn into a fad for me and turn to dust in the wind when I move on to another game. (I've already been down this road with Space Engineers before. I had an GUI for my reactors and everything.) But I do think that many aspiring engineers would love this as a possibility. 
	I can safely say that I understand the amount of work that goes into creating extensions like this and doubling up your workload is probably not advantageous nor effective, but if you could consider making a full blown switch after your next major revision is complete, the community would thank you for it. (You are THE recommended development environment, so to speak, for the in-game coding. So it may be worth your while.
	Thank you for taking the time to read this.
Sincerely,
	Some random guy on the internet who appreciates your effort enough to request more from you.

**Comment by malware-dev** [comment]
I wouldn't dream of hating on you for saying something that's as blatantly obvious as this. Please trust me when I say that I am _perfectly_ aware of the value of a '22 version and I hate that the compatibility layer was so poor - although I understand it.

But, this is a pure cost project for me, it does not - and will not ever, on purpose - bring any kind of income, and I'm in a fulltime programming job, so without the personal motivation to work on it, there's nothing.

**Comment by kennebel** [comment]
@malware-dev, I'd like to offer some help/extra hands. I haven't done a VS Extension before, but I hadn't done a VSCode extension before February of this year, and I now have an extension out there with over **_100_** downloads! :D (if you include the MS marketplace and the Open VSX marketplace) It looks like VS Extensions are C# based, so that will be easier for than me learning Typescript on top of learning to build extensions.

Please feel free to ping me if you are interested. I also have day jobs taking time, but I have a few hours here and there that I like to fill with coding.  --jac@kennebel.com

**Comment by malware-dev** [comment]
That is _very_ kind of you, @kennebel. I am _theoretically_ interested, but in practice it's not quite that simple. That would imply me having clear plans where I could delegate tasks. Currently MDK2 is in its planning, experimental and testing stage only. So there's nothing clear to delegate that couldn't potentially be completely scrapped or reworked.

MDK2 won't just be a VS extension. It will be far more loosely coupled. Primary reason being, I myself aren't using Visual Studio anymore, I use Jetbrains Rider. However, I can't fairly create an extension just for _that_ because it's a paid tool, as opposed to Visual Studio. So - I want to make the next iteration of MDK loose enough to be adapted for many IDEs - or even to be used just standalone, while still _having_ extensions - where needed - for at least Visual Studio and Rider.

**Comment by kennebel** [comment]
Thanks for the insight! Sounds like you have some really interesting plans for MDK2. I hope if it is right for you, that you can find the time. I'll definitely keep an eye out in case I can help in the future.

**Comment by Chaos02** [comment]
> 

oops - dont know how I missed that

**Comment by lloooll101** [comment]
So this will not work on VS2022? I have to download VS2019 in order to properly install MDK?

**Comment by malware-dev** [comment]
Yes, sorry
