### ISSUE TITLE
Using classes from separate files breaks the final script

### ISSUE THREAD

**Issue by julianbartel** [malware-dev/MDK-SE#35]
When a class is used from a separate file (no matter if from the same project or from a Shared Library), the final script is broken because it contains an invalid closing bracket between program part and extension part and the last closing bracket of the extension class gets removed.

I found this location in source code, which is propably the root cause? :-)
https://github.com/malware-dev/MDK-SE/blob/02b611fd751f155313552ef06302484a5fb6c730/Source/MDK/Build/ScriptGenerator.cs#L36-L37

**Comment by malware-dev** [comment]
Have you actually _tested this_? ;) This is by design.

You're writing extension classes here, not proper scripted classes. The generating is specifically made to work this way because it's _the only way_ to make them work. It's an officially sanctioned "exploit" - officially sanctioned because it's harmless.

You're supposed to use the UtilityClass template - or write your classes within Program partial classes. Because that's how Space Engineers scripts work.

**Comment by malware-dev** [comment]
https://github.com/malware-dev/MDK-SE/wiki/Utility-Class-or-Extension-Class%3F

Added this, because you're the second person to think this is a bug :D

**Comment by julianbartel** [comment]
Argh, sorry, forget about it!
> Have you actually _tested this_?

Of course not, my fault! ;) I was just confused because although intended and needed for extension classes, that behavior is applied to all classes. Anyway: I have never opened this issue :-D

**Comment by malware-dev** [comment]
Don't worry, it's _not_ all your fault. It's poorly described in the documentation. As you see I've made some changes I hope will help.

I see what you mean, but I do not entirely agree. A lot of scripters are completely new to coding. I want to lead them into the path of least resistance.
