### ISSUE TITLE
[Pre] Loading solutions from the R-Click Recent menu doesn't init MDK

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#62]
If if load solutions from the recent list from r-click on Vis Studio in the task bar, MDK doesn't allow 'deploy'.  But it is loaded.

![image](https://user-images.githubusercontent.com/18159679/38289317-688ccdf0-378a-11e8-85d7-675adab18859.png)

If I load Vis Studio and then choose from the Recent list, MDK *does* allow 'deploy'

![image](https://user-images.githubusercontent.com/18159679/38289339-84cfcb5c-378a-11e8-9ff6-2ad274791d4c.png)

**Comment by malware-dev** [comment]
Thank you. I'll check it out, but I seriously doubt I can do anything about how Visual Studio loads the projects...

**Comment by malware-dev** [comment]
It would have to be, in that case, since I haven't changed anything in the way MDK itself loads, I've just updated the script composer system. I'll be checking to see what's going on this weekend.

**Comment by malware-dev** [comment]
This seems to occur even when just starting solutions directly from explorer without starting Visual Studio first.

**Comment by baratgabor** [comment]
Oh, so this is why I had issues with Deploy not showing up?

By the way, I think this issue includes not showing the "Upgrade" dialog after updating MDK.

Because I started the solution multiple times (via the right-click method), and it never appeared. Now that I opened the solution after VS was already open, it popped up right away.

**Comment by malware-dev** [comment]
Yes, it would, because MDK is simply not told that there's a compatible project ready, and as such it won't do anything.
